routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [AuthController::class, 'home'])->name('home');

// -- AUTHENTIFICATION --
Route::get('/login', [AuthController::class, 'showLoginForm'])->name('loginForm');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/register', [AuthController::class, 'showRegisterForm'])->name('registerForm');
Route::post('/register', [AuthController::class, 'register'])->name('register');


Route::middleware('auth')->group(function () {
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

    // -- USER --                                                 NUR ADMIN
    Route::resource('/user', UserController::class)->middleware('can:isAdmin');

    // -- GROUPS --
    Route::resource('/group', GroupController::class);
    Route::post('/addgroup/{group_id}', [GroupController::class, 'addGroup'])->name('addGroup');
    Route::post('/group_leave/{group_id}', [GroupController::class, 'groupLeave'])->name('group_leave');
    Route::post('/group_update_admin/{group_id}/{admin_id}', [GroupController::class, 'groupUpdateAdmin'])->name('group_update_admin');
    Route::post('/group_delete_user/{group_id}/{user_id}', [GroupController::class, 'groupDeleteUser'])->name('group_delete_user');

    // -- QUESTIONS --
    Route::resource('/question', QuestionController::class);
    Route::get('/groupquestions/{group_id}', [QuestionController::class, 'showGroupQuestions'])->name('showGroupQuestions');
    Route::post('/question/{id}/update_level', [QuestionController::class, 'update_level']);

    // -- GAME --
    Route::view('/question/game/{group_id}', 'question.game')->name('question.game');
    Route::post('/game_start/{group_id}', [QuestionController::class, 'gameStart'])->name('gameStart');
    Route::post('/game/{id}/update_level', [QuestionController::class, 'game_update_level'])->name('game_update_level');
    Route::post('/group/{group_id}/reset_level', [QuestionController::class, 'reset_level'])->name('reset_level');
    Route::get('/game_end/{group_id}', [QuestionController::class, 'game_end'])->name('game_end');

    // -- COMMENTS --
    Route::resource('/comment', CommentController::class);
});

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Foundation\Application;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class QuestionController extends Controller
{
    public function showGroupQuestions(string $group_id)
    {
        $questions = DB::select('SELECT * FROM questions
         JOIN question_level ON questions.id = question_level.question_id
         WHERE group_id = ?
        AND question_level.user_id = ?
        ', [$group_id, Auth::id()]);
        return view('question.index', ['questions' => $questions, 'group_id' => $group_id]);
    }

    //Show the form for creating a new resource.
    public function create(): Factory|Application|View|\Illuminate\Contracts\Foundation\Application
    {
        return view('question.create');
    }

    //Store a newly created resource in storage.
    public function store(Request $request): RedirectResponse
    {

        $validatedData = $request->validate([
            'question' => 'required|max:255',
            'answer' => 'required|max:255',
            'group_id' => 'required'
        ]);

        $group_id = $validatedData['group_id'];

        DB::table('questions')->insert([
            'question' => $validatedData['question'],
            'answer' => $validatedData['answer'],
            'group_id' => $validatedData['group_id'],
            'user_id' => Auth::id()
        ]);

        $question_id = DB::select('SELECT id FROM questions order by id desc limit 1');

        $allGroupUsers = DB::select('SELECT user_id FROM user_in_group WHERE group_id = ?', [$group_id]);

        foreach ($allGroupUsers as $user) {
            DB::table('question_level')->insert([
                'user_id' => $user->user_id,
                'question_id' => $question_id[0]->id,
                'level' => 3
            ]);
        }

        return redirect()->route('showGroupQuestions', ['group_id' => $group_id])->with('success', 'Question Added successfully!.');
    }

    //Show the form for editing the specified resource.
    public function edit(string $id): Factory|Application|View|\Illuminate\Contracts\Foundation\Application
    {
        $question = DB::table('questions')->where('id', $id)->first();
        $questions = DB::select('SELECT * FROM questions');
        return view('question.edit', ['questions' => $questions, 'editquestion' => $question]);
    }

    //Update the specified resource in storage.
    public function update(Request $request, string $id)
    {
        $validatedData = $request->validate([
            'question' => 'required',
            'answer' => 'required',
        ]);

        DB::table('questions')->where('id', $id)->update([
            'question' => $validatedData['question'],
            'answer' => $validatedData['answer'],
        ]);
        return redirect('/question')->with('success', 'Question Updated successfully!.');
    }

    //Remove the specified resource from storage.
    public function destroy(string $id): Application|Redirector|\Illuminate\Contracts\Foundation\Application|RedirectResponse
    {
        DB::table('questions')->where('id', $id)->delete();
        return redirect('/question')->with('success', 'Question deleted successfully!.');
    }


   /*--------- Game funktions ---------*/


// spiel starten
    public function gameStart(string $group_id)
    {
        // get all questions
        $questions = DB::table('questions')
            ->join('question_level', 'questions.id', '=', 'question_level.question_id')
            ->where('group_id', $group_id)
            ->where('question_level.user_id', Auth::id())
            ->get();

        $count_level_one_questions = 0;

        // add question into question pool if the question->level is higher than 1
        foreach ($questions as $question) {
            if ($question->level == 3) {
                $questions[] = $question;
            }
            if ($question->level >= 2) {
                $questions[] = $question;
            }
            if ($question->level == 1) {
                $count_level_one_questions++;
            }
        }

        // end the game if all questions are level 1
        if ($questions->count() <= $count_level_one_questions) {
            return redirect()->route('game_end', [$group_id]);
        }

        // frage an view
        return view('question.game', ['question' => $questions->random(), 'group_id' => $group_id]);
    }

// spiel ende
    public function game_end($group_id)
    {
        $questions_ids = DB::table('question_level')
            ->join('questions', 'questions.id', '=', 'question_level.question_id')
            ->where('group_id', $group_id)
            ->where('question_level.user_id', Auth::id())
            ->get('question_id');

        foreach ($questions_ids as $question_id) {
            DB::table('question_level')
                ->where('user_id', Auth::id())
                ->where('question_id', $question_id->question_id)
                ->update(['level' => 3]);
        }
        return view('question.game_end');

    }

    public function game_update_level(Request $request, $id)
    {
        $question_id = $id;
        $action = $request->input('action');

        // aktuelles Level aus der Datenbank
        $currentLevel = DB::table('question_level')
            ->where('user_id', Auth::id())
            ->where('question_id', $question_id)
            ->value('level');

        if ($action == 'happy') {
            $newLevel = max($currentLevel - 1, 1);
        } elseif ($action == 'sad') {
            $newLevel = min($currentLevel + 1, 3);
        } else {
            $newLevel = $currentLevel;
        }

        DB::table('question_level')
            ->where('user_id', Auth::id())
            ->where('question_id', $question_id)
            ->update(['level' => $newLevel]);

        $group_id = DB::table('questions')->where('id', $question_id)->value('group_id');

        return $this->gameStart($group_id);
    }

    public function update_level(Request $request, $id)
    {
        $question_id = $id;
        $action = $request->input('action');

        // aktuelles Level aus der Datenbank
        $currentLevel = DB::table('question_level')
            ->where('user_id', Auth::id())
            ->where('question_id', $question_id)
            ->value('level');

        if ($action == 'happy') {
            $newLevel = max($currentLevel - 1, 1);
        } elseif ($action == 'sad') {
            $newLevel = min($currentLevel + 1, 3);
        } else {
            $newLevel = $currentLevel;
        }

        DB::table('question_level')
            ->where('user_id', Auth::id())
            ->where('question_id', $question_id)
            ->update(['level' => $newLevel]);

        $group_id = DB::table('questions')->where('id', $question_id)->value('group_id');

        return redirect()->back()->with('success', 'Level updated successfully!.');
    }
}

resources/views/question/comments.blade.php
@extends('layout.layout')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-1">
                <img src="{{ asset('img/msg.gif') }}" class="img position-fixed" alt="..." id="msg">
            </div>
            <div class="col-md-8 ">
                <div class="card mb-3">
                    <div class="card-body rounded" style="background-color: var(--soft-moss); color: var(--walnut-shell)">
                        <h5 class="card-title text-center mb-3">{{ $question->question }}</h5>
                        <p class="card-text text-center">{{ $question->answer }}</p>
                    </div>
                </div>

                <h5 class="display-4" style="color: var(--walnut-shell)">Kommentare</h5>

                <form action="{{route('comment.store')}}" method="post">
                    @csrf
                    <input type="hidden" name="question_id" value="{{$question->id}}">
                    <div class="input-group mb-3">
                        <input type="text" name="comment" value="{{old('comment')}}" class="form-control my-4" id="new-comment" placeholder="Neuer Kommentar" style="background-color: var(--misty-morning); color: var(--walnut-shell);">
                        @error('comment')
                        <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                        <button class="btn bg-gradient my-4" id="check_btn" style="background-color: var(--warm-beige); width: 5rem;" type="submit"><i class="fa-solid fa-check"></i></button>
                    </div>
                </form>
                {{--        All comments          --}}
                @foreach($comments as $comment)
                    <div class="card mb-3">
                        <div class="card-body bg-gradient" style="background-color: var(--warm-beige); color: var(--rich-soil);">
                            <h6 class="card-title"> <small style="color: var(--rich-soil); font-weight: bold">{{ $comment->name }}</small> <small style="color: var(--walnut-shell);">{{ $comment->created_at }}</small></h6>
                            <p class="card-text rounded py-1 px-3" style="width:42rem; background-color: var(--misty-morning); color: var(--walnut-shell);">{{ $comment->text }}</p>
                            @if($question->user_id == Auth::id() || $comment->user_id == Auth::id() || $group_admin_id[0]->admin_id == Auth::id())
                                <div class="container-fluid d-inline-flex justify-content-end p-0">
                                    <form action="{{route('comment.destroy', [$comment->id])}}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button class="btn bg-gradient py-2" style="background-color: var(--walnut-shell); color: var(--warm-beige);" type="submit">Löschen</button>
                                    </form>
                                </div>
                            @endif
                        </div>
                    </div>
                @endforeach
            </div>
            <div class="col-md-1">
                <img src="{{ asset('img/work.gif') }}" class="img position-fixed" alt="..." id="work">
            </div>
        </div>
    </div>
@endsection

resources/views/question/game.blade.php
@extends('layout.layout')
@section('content')
    <div class="container">
        <div class="row justify-content-center ">
            <div class="col-md-2">
                <img src="{{ asset('img/bubududu.gif') }}" class="img" alt="...">
            </div>
            <div class="col-1"></div>
            <div class="col-6" id="q-card_div">
                <div class="row" style="height: 50vh; width: 50vw;">
                <h2 class="text-center">{{ $question->question }}</h2>
                <div class="flip-card" style="height: 20rem;">
                    <div class="flip-card-inner" style="height: 20rem;">
                        <div class="flip-card-front" style="height: 20rem;">
                            <div class="card-body p-5 d-flex justify-content-center align-items-center" style="height: 20rem;">
                                <form action="{{route('comment.show', [$question->id])}}" method="get">
                                    @csrf
                                    <button type="submit" class="btn position-absolute top-0 end-0" id="chat_btn"><i class="fa-regular fa-comment"></i></button>
                                </form>
                                <h3 class="card-title">{{ $question->question }}</h3>
                            </div>
                        </div>
                        <div class="flip-card-back" style="height: 20rem;">
                            <div class="card-body p-3" style="height: 20rem;">

                                <p class="card-title mb-2" style="font-size: 1.2rem; height: 60%; overflow: scroll; ">{{ $question->answer }}</p>
                                <p>Level: {{ $question->level }}</p>

                                <div class="col d-inline-flex justify-content-center">
                                    <form action="{{ route('game_update_level', [$question->id]) }}" method="post">
                                        @csrf
                                        <input type="hidden" name="action" value="happy">
                                        <button type="submit" class="btn"><i class="fa-regular fa-face-smile" style="color: var(--rich-soil);"></i></button>
                                    </form>
                                    <form action="{{ route('game_update_level', [$question->id]) }}" method="post">
                                        @csrf
                                        <input type="hidden" name="action" value="neutral">
                                        <button type="submit" class="btn"><i class="fa-regular fa-face-meh" style="color: var(--rich-soil);"></i></button>
                                    </form>
                                    <form action="{{ route('game_update_level', [$question->id]) }}" method="post">
                                        @csrf
                                        <input type="hidden" name="action" value="sad">
                                        <button type="submit" class="btn"><i class="fa-regular fa-face-frown" style="color: var(--rich-soil);"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
            <div class="col-1"></div>
            <div class="col-md-2">
                <img src="{{ asset('img/peachcat-cat.gif') }}" class="img" alt="...">
            </div>
        </div>
    </div>
    <script src="{{ asset('js/flip-card.js') }}"></script>
@endsection

resources/views/question/game_end.blade.php
@extends('layout.layout')
@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center align-items-center">
            <div class="col-1"></div>
                <div class="col-md-2">
                    <img src="{{ asset('img/cheering.gif') }}" class="img" alt="...">
                </div>
                <div class="col-6 justify-content-center">
                    <h1 class="display-2 text-center mb-5" style="color: var(--walnut-shell)">Du hast alles geschafft!</h1>
                    <div class="d-flex justify-content-center">
                        <form action="{{ route('home') }}" method="get">
                            @csrf
                            <button class="btn bg-gradient p-2" style="background-color: var(--olive-grove); color: var(--warm-beige);" type="submit">Zurück zu Ihren Gruppen</button>
                        </form>
                    </div>
                </div>
                <div class="col-md-2">
                    <img src="{{ asset('img/cheering.gif') }}" class="img" alt="...">
                </div>
            <div class="col-1"></div>
        </div>
    </div>
@endsection

resources/views/question/index.blade.php
@extends('layout.layout')
@section('content')
    <div class="container">

        <div class="row">
            <div class="col-md-2 mx-4">
                <img src="{{ asset('img/thinking.gif') }}" class="img" id="thinking_img" alt="..." >
            </div>
            <div class="col-6 mb-5">
                <div class="card">
                    <div class="card-body rounded" style="background-color: var(--soft-moss);">
                        <form action="{{route('question.store')}}" method="POST">
                            @csrf
                            <div class="mb-3">
                                <label for="question" class="form-label">Frage</label>
                                <input type="text" name="question" value="{{old('question')}}" class="form-control @error('question') is-invalid @enderror" style="color:var(--rich-soil);">
                                @error('question')
                                <div class="invalid-feedback">
                                    {{$message}}
                                </div>
                                @enderror
                            </div>
                            <div>
                                <label for="answer" class="form-label">Antwort</label>
                                <textarea type="text" name="answer" class="form-control @error('answer') is-invalid @enderror" style="height: 10rem; color: var(--rich-soil);"></textarea>
                                @error('answer')
                                <div class="invalid-feedback">
                                    {{$message}}
                                </div>
                                @enderror
                            </div>
                            <div class="container-fluid d-inline-flex justify-content-end my-2">
                                <input type="hidden" name="group_id" value="{{$group_id}}">
                                <button type="submit" class="btn bg-gradient border-0 mt-2" style="background-color: var(--olive-grove); color: var(--warm-beige);">Frage hinzufügen</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="row g-4">
                    @foreach($questions as $question)
                        <div class="col-sm-3">
                            <div class="flip-card">
                                <div class="flip-card-inner">
                                    <div class="flip-card-front">
                                        <div class="card-body">
                                            {{--to go to commentars--}}

                                            <form action="{{route('comment.show', [$question->id])}}" method="get">
                                                @csrf
                                                <button type="submit" class="btn position-absolute top-0 end-0" id="chat_btn"><i class="fa-regular fa-comment"></i></button>
                                            </form>

                                            <h5 class="card-title">{{ $question->question }}</h5>
                                        </div>
                                    </div>
                                    <div class="flip-card-back">
                                        <div class="card-body" style="height: 10rem;">

                                            <p class="card-title mb-2" style="font-size: 1.2rem; height: 50%; overflow: scroll">{{ $question->answer }}</p>
                                            <p>Level: {{ $question->level }}</p>

                                            <div class="col d-inline-flex justify-content-center">
                                                <form action="/question/{{ $question->id }}/update_level" method="post">
                                                    @csrf
                                                    <input type="hidden" name="action" value="happy">
                                                    <button type="submit" class="btn"><i class="fa-regular fa-face-smile" style="color: var(--rich-soil);"></i></button>
                                                </form>
                                                <form action="/question/{{ $question->id }}/update_level" method="post">
                                                    @csrf
                                                    <input type="hidden" name="action" value="neutral">
                                                    <button type="submit" class="btn"><i class="fa-regular fa-face-meh" style="color: var(--rich-soil);"></i></button>
                                                </form>
                                                <form action="/question/{{ $question->id }}/update_level" method="post">
                                                    @csrf
                                                    <input type="hidden" name="action" value="sad">
                                                    <button type="submit" class="btn"><i class="fa-regular fa-face-frown" style="color: var(--rich-soil);"></i></button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
    <script src="{{ asset('js/flip-card.js') }}"></script>
@endsection