routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [AuthController::class, 'home'])->name('home');

// -- AUTHENTIFICATION --
Route::get('/login', [AuthController::class, 'showLoginForm'])->name('loginForm');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/register', [AuthController::class, 'showRegisterForm'])->name('registerForm');
Route::post('/register', [AuthController::class, 'register'])->name('register');


Route::middleware('auth')->group(function () {
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

    // -- USER --                                                 NUR ADMIN
    Route::resource('/user', UserController::class)->middleware('can:isAdmin');

    // -- GROUPS --
    Route::resource('/group', GroupController::class);
    Route::post('/addgroup/{group_id}', [GroupController::class, 'addGroup'])->name('addGroup');
    Route::post('/group_leave/{group_id}', [GroupController::class, 'groupLeave'])->name('group_leave');
    Route::post('/group_update_admin/{group_id}/{admin_id}', [GroupController::class, 'groupUpdateAdmin'])->name('group_update_admin');
    Route::post('/group_delete_user/{group_id}/{user_id}', [GroupController::class, 'groupDeleteUser'])->name('group_delete_user');

    // -- QUESTIONS --
    Route::resource('/question', QuestionController::class);
    Route::get('/groupquestions/{group_id}', [QuestionController::class, 'showGroupQuestions'])->name('showGroupQuestions');
    Route::post('/question/{id}/update_level', [QuestionController::class, 'update_level']);

    // -- GAME --
    Route::view('/question/game/{group_id}', 'question.game')->name('question.game');
    Route::post('/game_start/{group_id}', [QuestionController::class, 'gameStart'])->name('gameStart');
    Route::post('/game/{id}/update_level', [QuestionController::class, 'game_update_level'])->name('game_update_level');
    Route::post('/group/{group_id}/reset_level', [QuestionController::class, 'reset_level'])->name('reset_level');
    Route::get('/game_end/{group_id}', [QuestionController::class, 'game_end'])->name('game_end');

    // -- COMMENTS --
    Route::resource('/comment', CommentController::class);
});

resources/views/layout/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    @vite(['resources/js/app.js'])
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Learn cards</title>
    <link rel="stylesheet" href="{{asset('fontawesome-free-6.5.2-web\fontawesome-free-6.5.2-web\css\all.min.css')}}">
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
</head>
<body class="bg-body" id="whole_body py-3">

<nav class="navbar navbar-expand-lg p-2 bg-gradient" style="background-color: var(--rich-soil)">
    <div class="collapse navbar-collapse justify-content-xxl-between">
        <small class="text-center px-3" id="hello">Hi, {{ Auth::user()->name ?? 'Guest' }}</small>
        <ul class="navbar-nav">
            @if(Auth::check())
                <li class="nav-item">
                    <a class="nav-link" style="color: var(--warm-beige)" aria-current="page" href="{{route('home')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color: var(--warm-beige)" href="{{route('group.index')}}">Groups</a>
                </li>
                @can('isAdmin')
                    <li class="nav-item">
                        <a class="nav-link" style="color: var(--warm-beige)" href="{{route('user.index')}}">Users</a>
                    </li>
                @endcan
                <li class="nav-item">
                    <a class="nav-link" style="color: var(--warm-beige)" href="{{route('logout')}}">Logout</a>
                </li>
            @endif
        </ul>
    </div>
</nav>
<div class="container-fluid py-5" id="body">
    @section('content')
    @show
</div>
</body>
<footer class="blockquote-footer position-fixed bottom-0 container-fluid"
        style="background-color: transparent; color: var(--forest-floor)">
    @copyright Dani Ayat Dijana {{ date('Y') }}
</footer>
</html>