routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [AuthController::class, 'home'])->name('home');

// -- AUTHENTIFICATION --
Route::get('/login', [AuthController::class, 'showLoginForm'])->name('loginForm');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/register', [AuthController::class, 'showRegisterForm'])->name('registerForm');
Route::post('/register', [AuthController::class, 'register'])->name('register');


Route::middleware('auth')->group(function () {
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

    // -- USER --                                                 NUR ADMIN
    Route::resource('/user', UserController::class)->middleware('can:isAdmin');

    // -- GROUPS --
    Route::resource('/group', GroupController::class);
    Route::post('/addgroup/{group_id}', [GroupController::class, 'addGroup'])->name('addGroup');
    Route::post('/group_leave/{group_id}', [GroupController::class, 'groupLeave'])->name('group_leave');
    Route::post('/group_update_admin/{group_id}/{admin_id}', [GroupController::class, 'groupUpdateAdmin'])->name('group_update_admin');
    Route::post('/group_delete_user/{group_id}/{user_id}', [GroupController::class, 'groupDeleteUser'])->name('group_delete_user');

    // -- QUESTIONS --
    Route::resource('/question', QuestionController::class);
    Route::get('/groupquestions/{group_id}', [QuestionController::class, 'showGroupQuestions'])->name('showGroupQuestions');
    Route::post('/question/{id}/update_level', [QuestionController::class, 'update_level']);

    // -- GAME --
    Route::view('/question/game/{group_id}', 'question.game')->name('question.game');
    Route::post('/game_start/{group_id}', [QuestionController::class, 'gameStart'])->name('gameStart');
    Route::post('/game/{id}/update_level', [QuestionController::class, 'game_update_level'])->name('game_update_level');
    Route::post('/group/{group_id}/reset_level', [QuestionController::class, 'reset_level'])->name('reset_level');
    Route::get('/game_end/{group_id}', [QuestionController::class, 'game_end'])->name('game_end');

    // -- COMMENTS --
    Route::resource('/comment', CommentController::class);
});

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class GroupController extends Controller
{
    //Display a listing of the resource.
    public function index()
    {
        $groups = DB::select('SELECT * FROM groups
                                    JOIN user_in_group ON groups.id = user_in_group.group_id
                                    WHERE user_in_group.user_id LIKE ?', [Auth::id()]);

        return view('group.index', ['groups' => $groups]);
    }

    // Show the form for creating a new resource.
    public function create()
    {
        $groups = DB::select('SELECT * FROM groups EXCEPT SELECT groups.* FROM groups JOIN user_in_group ON groups.id = user_in_group.group_id WHERE user_in_group.user_id LIKE ?', [Auth::id()]);

        return view('group.create', ['groups' => $groups]);
    }

    //Store a newly created resource in storage.
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|unique:groups,name|max:255',
        ]);

        DB::table('groups')->insert([
            'name' => $validatedData['name'],
            'admin_id' => Auth::id(),
        ]);
        $newGroup = DB::table('groups')->orderBy('id', 'desc')->first();

        DB::table('user_in_group')->insert([
            'user_id' => Auth::id(),
            'group_id' => $newGroup->id,
        ]);

        return redirect()->route('group.index')->with('success', 'Group created successfully!.');
    }

    public function addGroup(string $group_id)
    {
        DB::table('user_in_group')->insert([
            'user_id' => Auth::id(),
            'group_id' => $group_id,
        ]);

        $questions = DB::select('SELECT id FROM questions where group_id = ?', [$group_id]);

        foreach ($questions as $question) {
            DB::insert('INSERT INTO question_level (user_id, question_id, level) VALUES (?, ?, ?)', [Auth::id(), $question->id, 3]);
        }

        return redirect()->route('showGroupQuestions', ['group_id' => $group_id]);

    }

    //Display the specified resource.
    public function show(string $id)
    {
        $group = DB::table('groups')->where('id', $id)->first();
        $users = DB::table('user_in_group')
            ->join('users', 'users.id', '=', 'user_in_group.user_id')
            ->where('group_id', $id)->get();

        return view('group.show', ['group' => $group, 'users' => $users]);
    }

    // Show the form for editing the specified resource.
    public function edit(string $id)
    {
        $group = DB::table('groups')->where('id', $id)->first();
        $users = DB::table('user_in_group')
            ->join('users', 'users.id', '=', 'user_in_group.user_id')
            ->where('group_id', $id)->get();
        return view('group.edit', ['group' => $group, 'users' => $users]);
    }

    // Update the specified resource in storage.
    public function update(Request $request, string $id)
    {
        $validatedData = $request->validate([
            'name' => 'required|max:255',
        ]);

        DB::table('groups')->where('id', $id)->update([
            'name' => $validatedData['name'],
        ]);
        return redirect()->route('group.index')->with('success', 'Produkt erfolgreich aktualisiert.');
    }

    public function groupUpdateAdmin(int $group_id, int $admin_id){
        DB::table('groups')->where('id', $group_id)->update([
            'admin_id' => $admin_id,
        ]);
        return redirect()->route('home');
    }

    //Remove the specified resource from storage.
    public function destroy(string $id)
    {
        $admin_id = DB::table('groups')->where('id', $id)->get('admin_id');

        if (Auth::id() == $admin_id[0]->admin_id) {
            DB::delete('DELETE question_level FROM question_level
                        JOIN questions ON questions.id = question_level.question_id
                        WHERE questions.group_id = ?', [$id]);
            DB::table('groups')->where('id', $id)->delete();
            DB::table('questions')->where('group_id', $id)->delete();
            DB::table('user_in_group')->where('group_id', $id)->delete();
        }

        return redirect()->route('group.index')->with('success', 'Group deleted successfully!.');
    }

    public function groupLeave(int $id)
    {
        // delete question_levels from this user
        DB::table('question_level')
            ->join('questions', 'questions.id', '=', 'question_level.question_id')
            ->where('questions.group_id', $id)
            ->where('question_level.user_id', Auth::id())
            ->delete();

        // delete user in group
        DB::delete('DELETE FROM user_in_group WHERE group_id = ? AND user_id = ?', [$id, Auth::id()]);

        $group_admin = DB::select('SELECT admin_id FROM groups WHERE id = ?', [$id]);
        $left_users_in_group = DB::select('SELECT user_id FROM user_in_group WHERE group_id = ?', [$id]);

        if ($group_admin[0]->admin_id == Auth::id()) {
            if ($left_users_in_group == null) {
                $this->destroy($id);
            } else {
                DB::table('groups')->where('id', $id)->update([
                    'admin_id' => $left_users_in_group[0]->user_id,
                ]);
            }
        }

        return redirect()->route('group.index');
    }

    public function groupDeleteUser(int $group_id, int $user_id){
        DB::table('user_in_group')->where('user_id', $user_id)->where('group_id', $group_id)->delete();
        $questions = DB::table('questions')->where('group_id', $group_id)->get('id');

        foreach ($questions as $question){
            DB::table('question_level')->where('user_id', $user_id)->where('question_id', $question->id)->delete();
        }
        return redirect()->back();
    }
}

resources/views/group/create.blade.php
@extends('layout.layout')
@section('content')
    <div class="row justify-content-center mx-5">
        <div class="col-md-3">
            <div class="card">
                <div class="card-header text-center bg-gradient"
                     style="background-color: var(--rich-soil); color: var(--warm-beige);">
                    <h3 class="card-title">Neue Gruppe</h3>
                </div>
                <div class="card-body bg-gradient" style="background-color: var(--warm-beige);">
                    <form action="{{route('group.store')}}" method="POST">
                        @csrf
                        <div class="form-group my-3">
                            <label for="name">Gruppenname:</label>
                            <input type="text" class="form-control" name="name"
                                   style="background-color: var(--misty-morning); color: var(--walnut-shell);">
                            @error('name')
                            <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="form-footer d-md-flex justify-content-md-end mt-4">
                            <button type="submit" class="btn bg-gradient"
                                    style="background-color: var(--olive-grove); color: var(--warm-beige);">Erstellen
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-9">
            <div class="row row-cols-1 row-cols-md-2 g-4">
                @foreach($groups as $group)
                    <div class="card p-0 mx-3" style="height: 12rem; width: 16rem; background-color: var(--warm-beige)">
                        <div class="card-header bg-gradient" style="background-color: var(--rich-soil);">
                            <h5 class="card-title" style="color: var(--warm-beige);">{{$group->name}}</h5>
                        </div>
                        <div class="card-body p-0">
                            <div class="row mb-3" style="height: 4.6rem;">
                                <img src="{{ asset('img/cheering.gif') }}" class="img"  id="cheering_img" alt="...">
                            </div>
                            <form  class="container-fluid d-inline-flex justify-content-end mx-0" action="{{route('addGroup', [$group->id])}}" method="POST">
                                @csrf
                                <button type="submit" class="btn bg-gradient" style="background-color: var(--olive-grove); color: var(--honeycomb);">Gruppe beitreten</button>
                            </form>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/group/edit.blade.php
@extends('layout.layout')
@section('content')
    <div class="d-flex justify-content-between p-5">
        <div class="col-6">
            <div class="card">
                <div class="card-header bg-gradient"
                     style="background-color: var(--rich-soil); color: var(--warm-beige);">
                    <div class="display-5 my-2" > {{ $group->name }} </div>
                </div>
                <div class="card-body" style="background-color: var(--soft-moss); color: var(--walnut-shell);">
                    <form action="{{route('group.update', [$group->id])}}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="form-group p-3 mb-2">
                            <label for="name" class="col-form-label-lg">Gruppenname:</label>
                            <input type="text" name="name" class="form-control" value="{{$group->name}}">
                            @error('name')
                            <small class="text-danger">{{ $message }}</small>
                            @enderror
                        </div>
                        <div class="d-flex justify-content-end">
                            <button type="submit" class="btn bg-gradient mx-3 mb-5" style="background-color: var(--olive-grove); color: var(--warm-beige);">Speichern</button>
                        </div>
                    </form>
                    <div class="container-fluid d-flex justify-content-center my-3">
                        <div class="card col-md-12">
                            <div class="card-body rounded" style="background-color: var(--soft-moss);">
                                <table class="table table-hover table-sm">
                                    <thead>
                                    <tr class="table-borderless bg-gradient">
                                        <th class="col-1" style="color: var(--warm-beige); background-color: var(--rich-soil); ">ID</th>
                                        <th class="col-10" style="color: var(--warm-beige); background-color: var(--rich-soil);">Name</th>
                                        <th class="col-1 " style="color: var(--warm-beige); background-color: var(--rich-soil);">Aktionen</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach ($users as $user)
                                        <tr>
                                            <td style="color: var(--rich-soil)">{{ $user->id }}</td>
                                            @if($user->id == Auth::id())
                                                <td style="color: var(--rich-soil)">Du</td>
                                                <td style="width: 20rem"></td>
                                            @else
                                                <td style="color: var(--rich-soil)">{{ $user->name }}</td>

                                                <td class="col d-inline-flex" style="width: 6rem;">
                                                    <form action="{{ route('group_update_admin', [$group->id, $user->id]) }}" method="post">
                                                        @csrf
                                                        <button type="submit" class="btn bg-gradient"><i id="crown" class="fa-solid fa-crown"></i></button>
                                                    </form>
                                                    <form action="{{  route('group_delete_user', [$group->id, $user->id])}}" method="POST">
                                                        @csrf
                                                        <button class="btn" type="submit"><i id="trash_icon" class="fa-regular fa-trash-can"></i></button>
                                                    </form>
                                                </td>
                                            @endif
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="container d-inline-flex justify-content-between">
                        <a href="{{route('home')}}" class="btn bg-gradient" style="background-color: var(--walnut-shell); color: var(--warm-beige);">Züruck</a>
                        <form action="{{route('group.destroy', [$group->id])}}" method="post">
                            @csrf
                            @method('delete')
                            <input type="submit" value="Gruppe löschen" class="btn bg-gradient" style="background-color: var(--olive-grove); color: var(--warm-beige);">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <img src="{{ asset('img/sleepy.gif') }}" class="img" alt="...">
        </div>
    </div>
@endsection

resources/views/group/index.blade.php
@extends('layout.layout')
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="row d-inline-flex justify-content-between">
                <h1 class="col display-1 my-3" style="color: var(--walnut-shell)">Gruppen:</h1>
                <div class="col-md-2">
                    <img src="{{ asset('img/dancers.gif') }}" class="img mx-3" alt="..." id="dancers_img">
                </div>
            </div>
            <div class="row mx-1">
                <a href="{{route('group.create')}}" class="btn bg-gradient my-3 py-2" style="width: 15rem; background-color: var(--olive-grove); color: var(--warm-beige)">Gruppe hinzufügen</a>
            </div>
            <div class="row g-4">
                @foreach($groups as $group)
                    <div class="col-sm-2">
                        <div class="card" style="height: 13rem">
                            <div class="card-header bg-gradient"
                                 style="background-color: var(--rich-soil); color: var(--warm-beige);">
                                <h5 class="card-title">{{$group->name}}</h5>
                            </div>
                            <div class="card-body bg-gradient" style="background-color: var(--warm-beige);">
                                <div class="d-flex justify-content-start my-3">
                                    <form action="{{route('group.show', [$group->id])}}" method="GET">
                                        @csrf
                                        <input type="submit" value="Gruppe anzeigen" class="btn bg-gradient" style="background-color: var(--forest-floor); color: var(--warm-beige); width: 9rem;">
                                    </form>
                                @if($group->admin_id == Auth::id())
                                        <form action="{{ route('group.edit', [$group->id]) }}" method="GET">
                                            @csrf
                                            <button type="submit" class="btn">
                                                <i class="fa-solid fa-pen-to-square"></i>
                                            </button>
                                        </form>
                                    @endif
                                </div>
                                <div class="d-flex justify-content-end">
                                    <form action="{{ route('group_leave', [$group->id]) }}" method="POST">
                                        @csrf
                                        <button type="submit" class="btn">
                                            <i style="color: salmon;" class="fa-solid fa-door-open"></i>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

resources/views/group/show.blade.php
@extends('layout.layout')
@section('content')
    <div class="display-2 m-3" style="color: var(--walnut-shell);"> {{$group->name}} </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 mx-3">
                <div class="card">
                    <div class="card-header bg-gradient" style="background-color: var(--rich-soil); color: var(--warm-beige);">
                        <div class="display-2"> Mitglieder </div>
                    </div>
                    <div class="card-body" style="background-color: var(--soft-moss); color: var(--walnut-shell);">
                        <table class="table table-hover">
                            <thead>
                            <tr class="table-borderless">
                                <th scope="col" class="col-11" style="color: var(--walnut-shell);">Name</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach( $users as $user )
                                    <tr>
                                        <td style="color: var(--walnut-shell);">
                                            {{ $user->name }}
                                            @if($user->id == $group->admin_id)
                                                <i class="fa-solid fa-crown mx-1" style="color: var(--honeycomb); font-size: 1rem;"></i>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                            <div class="d-flex justify-content-between">
                                <form action="{{ route('gameStart', [$group->id]) }}" method="post">
                                    @csrf
                                    <input type="submit" value="Starte die Abfrage" class="btn bg-gradient" style="background-color: var(--olive-grove); color: var(--warm-beige);">
                                </form>

                                <form action="{{route('showGroupQuestions', ['group_id' => $group->id])}}" method="get">
                                    @csrf
                                    <input type="submit" value="Fragen" class="btn bg-gradient" style="background-color: var(--olive-grove); color: var(--warm-beige);">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="col-md-4 mx-4">
                <img src="{{ asset('img/dancers.gif') }}" class="img" alt="...">
            </div>
        </div>
    </div>
@endsection