routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\CommentController;
use App\Http\Controllers\GroupController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [AuthController::class, 'home'])->name('home');

// -- AUTHENTIFICATION --
Route::get('/login', [AuthController::class, 'showLoginForm'])->name('loginForm');
Route::post('/login', [AuthController::class, 'login'])->name('login');
Route::get('/register', [AuthController::class, 'showRegisterForm'])->name('registerForm');
Route::post('/register', [AuthController::class, 'register'])->name('register');


Route::middleware('auth')->group(function () {
    Route::get('/logout', [AuthController::class, 'logout'])->name('logout');

    // -- USER --                                                 NUR ADMIN
    Route::resource('/user', UserController::class)->middleware('can:isAdmin');

    // -- GROUPS --
    Route::resource('/group', GroupController::class);
    Route::post('/addgroup/{group_id}', [GroupController::class, 'addGroup'])->name('addGroup');
    Route::post('/group_leave/{group_id}', [GroupController::class, 'groupLeave'])->name('group_leave');
    Route::post('/group_update_admin/{group_id}/{admin_id}', [GroupController::class, 'groupUpdateAdmin'])->name('group_update_admin');
    Route::post('/group_delete_user/{group_id}/{user_id}', [GroupController::class, 'groupDeleteUser'])->name('group_delete_user');

    // -- QUESTIONS --
    Route::resource('/question', QuestionController::class);
    Route::get('/groupquestions/{group_id}', [QuestionController::class, 'showGroupQuestions'])->name('showGroupQuestions');
    Route::post('/question/{id}/update_level', [QuestionController::class, 'update_level']);

    // -- GAME --
    Route::view('/question/game/{group_id}', 'question.game')->name('question.game');
    Route::post('/game_start/{group_id}', [QuestionController::class, 'gameStart'])->name('gameStart');
    Route::post('/game/{id}/update_level', [QuestionController::class, 'game_update_level'])->name('game_update_level');
    Route::post('/group/{group_id}/reset_level', [QuestionController::class, 'reset_level'])->name('reset_level');
    Route::get('/game_end/{group_id}', [QuestionController::class, 'game_end'])->name('game_end');

    // -- COMMENTS --
    Route::resource('/comment', CommentController::class);
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;

class UserController extends Controller
{
    //Display a listing of the resource.

    public function index()
    {
        if (Auth::check()) {
            if (Gate::allows('isAdmin')) {
                $users = DB::select('SELECT * FROM users');
                return view('user.index', ['users' => $users]); //, 'editProduct' => null]);
            }
        }
        return redirect('/');
    }

    //Store a newly created resource in storage.
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|unique:users|max:255',
        ]);

        DB::table('groups')->insert([
            'name' => $validatedData['name'],
        ]);

        return redirect()->route('user.index')->with('success', 'User created successfully!.');
    }

    // Show the form for editing the specified resource.
    public function edit(string $id)
    {
        if (Auth::check()) {
            if (Gate::allows('isAdmin')) {
                $user = DB::table('users')->where('id', $id)->first();
                $users = DB::select('SELECT * FROM users');

                if ($user) {
                    return view('user.edit', compact('user'));
                }
                return view('index')->with('error', 'User not found!');
            }
        }
        return redirect('/');
    }

    // Update the specified resource in storage.
    public function update(Request $request, string $id)
    {
        if (Auth::check()) {
            if (Gate::allows('isAdmin')) {
                $validatedData = $request->validate([
                    'name' => 'required|max:255'
                ]);

                DB::table('users')->where('id', $id)->update([
                    'name' => $validatedData['name']
                ]);
                return redirect()->route('user.index')->with('success', 'User updated successfully!.');
            }
        }
        return redirect('/');
    }

    //Remove the specified resource from storage.
    public function destroy(string $id)
    {
        if (Auth::check()) {
            if (Gate::allows('isAdmin')) {
                $userIdToDestroy = $id;
                DB::table('question_level')->where('user_id', $userIdToDestroy)->delete();
                $user_in_group_list = DB::table('user_in_group')->where('user_id', $userIdToDestroy)->get();
                foreach ($user_in_group_list as $user_in_group_l) {
                    $group = DB::table('groups')->where('id', $user_in_group_l->group_id)->first();

                    if ($group->admin_id == $userIdToDestroy) {
                        $users_in_group = DB::table('user_in_group')->where('group_id', $group->id)->get();
                        if (sizeof($users_in_group) > 1) {
                            foreach ($users_in_group as $user_in_group) {
                                if ($user_in_group->user_id != $userIdToDestroy) {
                                    DB::table('groups')->where('id', $user_in_group->group_id)->update([
                                        'admin_id' => $user_in_group->user_id,
                                    ]);
                                    break;
                                }
                            }
                        }
                        else {
                            DB::delete('DELETE question_level FROM question_level
                        JOIN questions ON questions.id = question_level.question_id
                        WHERE questions.group_id = ?', [$group->id]);
                            DB::table('groups')->where('id', $group->id)->delete();
                            DB::table('questions')->where('group_id', $group->id)->delete();
                        }
                    }
                }
                DB::table('user_in_group')->where('user_id', $userIdToDestroy)->delete();
                DB::table('users')->where('id', $userIdToDestroy)->delete();

                return redirect('/user')->with('success', 'User deleted successfully!.');
            }
        }
        return redirect('/');
    }
}

resources/views/user/edit.blade.php
@extends('layout.layout')
@section('content')
    <div class="container-fluid d-inline-flex justify-content-between">
        <h1 class="display-3 text-center mb-5" style="color: var(--walnut-shell)">Benutzer bearbeiten</h1>
        <div class="col-md-2">
            <img src="{{ asset('img/cheering.gif') }}" class="img mx-3" alt="..." style="font-size: 3rem;">
        </div>
    </div>
    <div class="container-fluid d-flex justify-content-center">
        <div class="card col-md-12">
            <div class="card-body" style="background-color: var(--soft-moss);">
                <form action="{{ route('user.update', $user->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <table class="table table-hover">
                        <thead>
                        <tr class="table-borderless">
                            <th class="col bg-gradient" style="color: var(--warm-beige); background-color: var(--rich-soil); font-size: 2rem;">ID</th>
                            <th class="col bg-gradient" style="color: var(--warm-beige); background-color: var(--rich-soil); font-size: 2rem;">Name</th>
                            <th class="col-sm bg-gradient" style="color: var(--warm-beige); background-color: var(--rich-soil); font-size: 2rem;">Aktionen</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td style="color: var(--rich-soil);">{{ $user->id }}</td>
                            <td style="color: var(--rich-soil);">
                                <input type="text" name="name" value="{{ $user->name }}" class="form-control">
                            </td>
                            <td style="width: 20rem">
                                <button type="submit" class="btn"><i class="fa-regular fa-circle-check"></i></button>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layout.layout')
@section('content')
    <div class="container-fluid d-inline-flex justify-content-between">
        <h1 class="display-3 text-center mb-5" style="color: var(--walnut-shell)">Die Liste von Benutzers</h1>
        <div class="col-md-2">
            <img src="{{ asset('img/cheering.gif') }}" class="img mx-3" alt="..." style="font-size: 3rem;">
        </div>
    </div>
    <div class="container-fluid d-flex justify-content-center">
        <div class="card col-md-12">
            <div class="card-body" style="background-color: var(--soft-moss);">
                <table class="table table-hover">
                    <thead>
                    <tr class="table-borderless">
                        <th class="col bg-gradient" style="color: var(--warm-beige); background-color: var(--rich-soil); font-size: 2rem;">ID</th>
                        <th class="col bg-gradient" style="color: var(--warm-beige); background-color: var(--rich-soil); font-size: 2rem;">Name</th>
                        <th class="col bg-gradient" style="color: var(--warm-beige); background-color: var(--rich-soil); font-size: 2rem;">Email</th>
                        <th class="col-sm bg-gradient" style="color: var(--warm-beige); background-color: var(--rich-soil); font-size: 2rem;">Aktionen</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($users as $user)
                        <tr>
                            <td style="color: var(--rich-soil);">{{ $user->id }}</td>
                            <td style="color: var(--rich-soil)">{{ $user->name }}</td>
                            <td style="color: var(--rich-soil)">{{ $user->email }}</td>
                            <td style="width: 20rem">
                                <div class="btn-group">
                                    <form action="" method="GET">
                                        @csrf
                                        <button formaction="{{ route('user.edit', $user->id) }}" class="btn bg-gradient"><i class="fa-solid fa-pen-to-square"></i></button>
                                    </form>
                                    <form action="" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button formaction="{{ route('user.destroy', $user->id) }}" class="btn mx-4"><i style="color: salmon" class="fa-regular fa-trash-can"></i></button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection